[tool.poetry]
name = "albert"
version = "0.1.0"
description = ""
authors = ["lookie <ilookie@163.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
logzero = "^1.7.0"
scapy = "^2.5.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
